# Generated by Django 5.1.2 on 2024-10-25 07:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('payslip', 'Payslip'), ('spouse_id', 'Spouse ID'), ('next_of_kin_id', 'Next of Kin ID'), ('birth_certificate', 'Birth Certificate'), ('ncpwd_card', 'NCPWD Card'), ('appointment_letter', 'Appointment Letter'), ('logbook', 'Logbook'), ('sale_agreement', 'Sale Agreement'), ('pin_certificate', 'PIN Certificate'), ('proforma_invoice', 'Proforma Invoice'), ('valuation_report', 'Valuation Report'), ('payment_proof', 'Payment Proof'), ('hr_letter', 'HR Letter'), ('bank_statement', 'Bank Statement'), ('bank_details', 'Bank Details')], max_length=50)),
                ('document', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'jpg'])])),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_validated', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('repayment_period', models.PositiveIntegerField(default=12)),
                ('vehicle_make', models.CharField(default='Unknown', max_length=50)),
                ('vehicle_model', models.CharField(default='Unknown', max_length=50)),
                ('vehicle_year', models.PositiveIntegerField(default=2000)),
                ('vehicle_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('insurance_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_loan_required', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_details', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], default='Mr', max_length=5)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('spouse_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ministry_department', models.CharField(max_length=100)),
                ('job_group_scale', models.CharField(max_length=50)),
                ('current_net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='applications.application')),
            ],
        ),
    ]
