# Generated by Django 5.1.2 on 2024-10-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='documentupload',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='tracking_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('payslip', 'Payslip'), ('spouse_id', 'Spouse ID'), ('next_of_kin_id', 'Next of Kin ID'), ('birth_certificate', 'Birth Certificate'), ('ncpwd_card', 'NCPWD Card'), ('appointment_letter', 'Appointment Letter'), ('logbook', 'Logbook'), ('sale_agreement', 'Sale Agreement'), ('pin_certificate', 'PIN Certificate'), ('proforma_invoice', 'Proforma Invoice'), ('valuation_report', 'Valuation Report'), ('payment_proof', 'Payment Proof'), ('hr_letter', 'HR Letter'), ('bank_statement', 'Bank Statement'), ('bank_details', 'Bank Details')], max_length=50),
        ),
    ]
