# Generated by Django 5.1.2 on 2024-11-13 06:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationtracker_documentupload_is_validated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='employment_details',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='name',
        ),
        migrations.AddField(
            model_name='documentupload',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loandetails',
            name='insurance_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loandetails',
            name='total_loan_required',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loandetails',
            name='vehicle_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=10000.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='current_net_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='job_group_scale',
            field=models.CharField(choices=[('L', 'L'), ('M', 'M'), ('N', 'N'), ('R', 'R')], default='L', max_length=50),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='other_names',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='surname',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], default='Mr', max_length=5),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_details', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='repayment_period',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='vehicle_make',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='vehicle_model',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='vehicle_year',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='ministry_department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='national_id',
            field=models.CharField(default='00000000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='spouse_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
