# Generated by Django 5.1.2 on 2024-11-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_personaldetails_employment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='date_of_current_appointment',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='date_of_first_appointment',
            field=models.DateField(default='2005-01-01'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='designation',
            field=models.CharField(default='Employee', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='disability_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='email_address',
            field=models.EmailField(default='john.doe@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='next_of_kin',
            field=models.CharField(default='Jane Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='next_of_kin_id',
            field=models.CharField(default='NOK0001', max_length=20),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='next_of_kin_mobile',
            field=models.CharField(default='0712345678', max_length=15),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='next_of_kin_relationship',
            field=models.CharField(default='Sibling', max_length=50),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='personal_no',
            field=models.CharField(default='P0000000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='physical_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='residential_address',
            field=models.CharField(default='123 Default Street', max_length=200),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='terms_of_service',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], default='Permanent', max_length=50),
        ),
    ]
