# Generated by Django 5.1.2 on 2024-11-13 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_personaldetails_contract_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='allocated_amount',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='current_net_salary',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='date_of_current_appointment',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='date_of_first_appointment',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='job_group_scale',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='ministry_department',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='terms_of_service',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Employee', max_length=100)),
                ('date_of_first_appointment', models.DateField(default='2005-01-01')),
                ('date_of_current_appointment', models.DateField(default='2020-01-01')),
                ('terms_of_service', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], default='Permanent', max_length=50)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('ministry_department', models.CharField(default='General', max_length=100)),
                ('job_group_scale', models.CharField(choices=[('L', 'L'), ('M', 'M'), ('N', 'N'), ('R', 'R')], default='L', max_length=50)),
                ('current_net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=10000.0, editable=False, max_digits=10)),
                ('personal_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_details', to='applications.personaldetails')),
            ],
        ),
    ]
